## PyTorch Linear Regression Model 

In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

In [2]:
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
display(x_train)
x_train = x_train.reshape(-1, 1)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
display(y_train)
y_train = y_train.reshape(-1, 1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21.],
      dtype=float32)

### for GPU. Only the model and Variable need the .cuda()

In [3]:
torch.cuda.is_available()

False

In [4]:
'''
CREATE MODEL CLASS
'''
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)  
    
    def forward(self, x):
        out = self.linear(x)
        return out

'''
INSTANTIATE MODEL CLASS
'''
input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

#######################
#  USE GPU FOR MODEL  #
#######################
if torch.cuda.is_available():
    model.cuda()

'''
INSTANTIATE LOSS CLASS
'''

criterion = nn.MSELoss()

'''
INSTANTIATE OPTIMIZER CLASS
'''

learning_rate = 0.01

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [5]:
'''
TRAIN THE MODEL
'''
epochs = 20
for epoch in range(epochs):
    epoch += 1
    # Convert numpy array to torch Variable
    
    #######################
    #  USE GPU FOR MODEL  #
    #######################
    if torch.cuda.is_available():
        inputs = Variable(torch.from_numpy(x_train).cuda())
        labels = Variable(torch.from_numpy(y_train).cuda())
    else:
        inputs = Variable(torch.from_numpy(x_train))
        labels = Variable(torch.from_numpy(y_train))

        
    # Clear gradients w.r.t. parameters
    optimizer.zero_grad() 
    
    # Forward to get output
    outputs = model(inputs)
    
    # Calculate Loss
    loss = criterion(outputs, labels)
    
    # Getting gradients w.r.t. parameters
    loss.backward()
    
    # Updating parameters
    optimizer.step()
    
    # Logging
    print('epoch {}, loss {}'.format(epoch, loss.data[0]))

epoch 1, loss 334.15386962890625
epoch 2, loss 27.413524627685547
epoch 3, loss 2.3919179439544678
epoch 4, loss 0.34924376010894775
epoch 5, loss 0.1809081733226776
epoch 6, loss 0.16547562181949615
epoch 7, loss 0.16253381967544556
epoch 8, loss 0.16062963008880615
epoch 9, loss 0.15882858633995056
epoch 10, loss 0.15705443918704987
epoch 11, loss 0.15530049800872803
epoch 12, loss 0.1535663604736328
epoch 13, loss 0.15185140073299408
epoch 14, loss 0.15015578269958496
epoch 15, loss 0.14847904443740845
epoch 16, loss 0.14682090282440186
epoch 17, loss 0.14518140256404877
epoch 18, loss 0.14356008172035217
epoch 19, loss 0.1419571489095688
epoch 20, loss 0.1403719037771225


### Compare Data

In [7]:
if torch.cuda.is_available():
    predicted=model(Variable(torch.from_numpy(x_train).cuda())).data.cpu().numpy()
else:
    predicted=model(Variable(torch.from_numpy(x_train))).data.numpy()
predicted

array([[ 0.30305207],
       [ 2.403419  ],
       [ 4.5037856 ],
       [ 6.6041527 ],
       [ 8.704519  ],
       [10.804886  ],
       [12.905253  ],
       [15.00562   ],
       [17.105988  ],
       [19.206354  ],
       [21.30672   ]], dtype=float32)

In [8]:
y_train

array([[ 1.],
       [ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.],
       [13.],
       [15.],
       [17.],
       [19.],
       [21.]], dtype=float32)

### Save & Retrieve the model

In [26]:
torch.save(model.state_dict(),'linearregression_model.pkl')

In [27]:
model.load_state_dict(torch.load('linearregression_model.pkl'))