## PyTorch Linear Regression Model 

In [6]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

In [7]:
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
display(x_train)
x_train = x_train.reshape(-1, 1)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
display(y_train)
y_train = y_train.reshape(-1, 1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21.],
      dtype=float32)

### for GPU. Only the model and Variable need the .cuda()

In [10]:
torch.cuda.is_available()

True

In [3]:
'''
CREATE MODEL CLASS
'''
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)  
    
    def forward(self, x):
        out = self.linear(x)
        return out

'''
INSTANTIATE MODEL CLASS
'''
input_dim = 1
output_dim = 1

model = LinearRegressionModel(input_dim, output_dim)

#######################
#  USE GPU FOR MODEL  #
#######################
if torch.cuda.is_available():
    model.cuda()

'''
INSTANTIATE LOSS CLASS
'''

criterion = nn.MSELoss()

'''
INSTANTIATE OPTIMIZER CLASS
'''

learning_rate = 0.01

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [4]:
'''
TRAIN THE MODEL
'''
epochs = 20
for epoch in range(epochs):
    epoch += 1
    # Convert numpy array to torch Variable
    
    #######################
    #  USE GPU FOR MODEL  #
    #######################
    if torch.cuda.is_available():
        inputs = Variable(torch.from_numpy(x_train).cuda())
        labels = Variable(torch.from_numpy(y_train).cuda())
    else:
        inputs = Variable(torch.from_numpy(x_train))
        labels = Variable(torch.from_numpy(y_train))

        
    # Clear gradients w.r.t. parameters
    optimizer.zero_grad() 
    
    # Forward to get output
    outputs = model(inputs)
    
    # Calculate Loss
    loss = criterion(outputs, labels)
    
    # Getting gradients w.r.t. parameters
    loss.backward()
    
    # Updating parameters
    optimizer.step()
    
    # Logging
    print('epoch {}, loss {}'.format(epoch, loss.data[0]))

epoch 1, loss 234.4321746826172
epoch 2, loss 19.195232391357422
epoch 3, loss 1.6382153034210205
epoch 4, loss 0.2053356021642685
epoch 5, loss 0.08765951544046402
epoch 6, loss 0.0772690549492836
epoch 7, loss 0.07563848048448563
epoch 8, loss 0.07473134249448776
epoch 9, loss 0.07389165461063385
epoch 10, loss 0.0730661004781723
epoch 11, loss 0.072250135242939
epoch 12, loss 0.07144337147474289
epoch 13, loss 0.07064550369977951
epoch 14, loss 0.06985669583082199
epoch 15, loss 0.06907660514116287
epoch 16, loss 0.06830517947673798
epoch 17, loss 0.06754240393638611
epoch 18, loss 0.0667882189154625
epoch 19, loss 0.0660424456000328
epoch 20, loss 0.06530498713254929


### Compare Data

In [11]:
predicted=model(Variable(torch.from_numpy(x_train).cuda())).data.cpu().numpy()
predicted

array([[ 0.52462834],
       [ 2.5930862 ],
       [ 4.661544  ],
       [ 6.730002  ],
       [ 8.79846   ],
       [10.866918  ],
       [12.935375  ],
       [15.003833  ],
       [17.07229   ],
       [19.140749  ],
       [21.209208  ]], dtype=float32)

In [12]:
y_train

array([[ 1.],
       [ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.],
       [13.],
       [15.],
       [17.],
       [19.],
       [21.]], dtype=float32)

### Save & Retrieve the model

In [26]:
torch.save(model.state_dict(),'linearregression_model.pkl')

In [27]:
model.load_state_dict(torch.load('linearregression_model.pkl'))