## PyTorch Linear Regression Model 

In [33]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

In [34]:
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
x_train = x_train.reshape(-1, 1)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
y_train = y_train.reshape(-1, 1)

x_train, y_train

(array([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]], dtype=float32), array([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.],
        [13.],
        [15.],
        [17.],
        [19.],
        [21.]], dtype=float32))

### Use .to(device) to determine where to run the model
### - Also make sure the inputs are sent to the same device

In [45]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
#override device
device=torch.device("cuda:0")
print(device)

cuda:0


In [46]:
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)  
    
    def forward(self, x):
        out = self.linear(x)
        return out


model = LinearRegressionModel(1, 1).to(device)

#if torch.cuda.is_available():
#    model.cuda()

criterion = nn.MSELoss()

learning_rate = 0.01

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [47]:
epochs = 20
for epoch in range(epochs):
    epoch += 1
#    if torch.cuda.is_available():
#        inputs = torch.from_numpy(x_train).cuda()
#        labels = torch.from_numpy(y_train).cuda()
#    else:
    inputs = torch.from_numpy(x_train).to(device)
    labels = torch.from_numpy(y_train).to(device)
    
    # Forward propagation
    outputs = model(inputs)
    
    loss = criterion(outputs, labels)
    
    # Backward propagation
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()     
    
    # Logging
    print('epoch {}, loss {}'.format(epoch, loss.data))

epoch 1, loss 224.94873046875
epoch 2, loss 18.386693954467773
epoch 3, loss 1.5376566648483276
epoch 4, loss 0.16290909051895142
epoch 5, loss 0.050356701016426086
epoch 6, loss 0.04076218605041504
epoch 7, loss 0.03957022726535797
epoch 8, loss 0.03906826302409172
epoch 9, loss 0.038627080619335175
epoch 10, loss 0.03819535672664642
epoch 11, loss 0.03776878863573074
epoch 12, loss 0.03734702989459038
epoch 13, loss 0.03692999482154846
epoch 14, loss 0.036517634987831116
epoch 15, loss 0.03610982373356819
epoch 16, loss 0.03570658341050148
epoch 17, loss 0.0353078693151474
epoch 18, loss 0.034913595765829086
epoch 19, loss 0.034523699432611465
epoch 20, loss 0.034138184040784836


### Compare Data

In [48]:
if torch.cuda.is_available():
    predicted=model(torch.from_numpy(x_train).cuda()).data.cpu().numpy()
else:
    predicted=model(torch.from_numpy(x_train)).data.numpy()
predicted

array([[ 0.65629923],
       [ 2.7057953 ],
       [ 4.755291  ],
       [ 6.804787  ],
       [ 8.854283  ],
       [10.903779  ],
       [12.953275  ],
       [15.00277   ],
       [17.052267  ],
       [19.101763  ],
       [21.151258  ]], dtype=float32)

In [49]:
y_train

array([[ 1.],
       [ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.],
       [13.],
       [15.],
       [17.],
       [19.],
       [21.]], dtype=float32)

### Save & Retrieve the model

In [26]:
torch.save(model.state_dict(),'linearregression_model.pkl')

In [27]:
model.load_state_dict(torch.load('linearregression_model.pkl'))