## PyTorch Linear Regression Model 

In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

In [2]:
x_values = [i for i in range(11)]
x_train = np.array(x_values, dtype=np.float32)
display(x_train)
x_train = x_train.reshape(-1, 1)

y_values = [2*i + 1 for i in x_values]
y_train = np.array(y_values, dtype=np.float32)
display(y_train)
y_train = y_train.reshape(-1, 1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21.],
      dtype=float32)

### for GPU. Only the model and Variable need the .cuda()

In [3]:
torch.cuda.is_available()

False

In [4]:
class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)  
    
    def forward(self, x):
        out = self.linear(x)
        return out


model = LinearRegressionModel(1, 1)

if torch.cuda.is_available():
    model.cuda()

criterion = nn.MSELoss()

learning_rate = 0.01

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [6]:
epochs = 20
for epoch in range(epochs):
    epoch += 1
    if torch.cuda.is_available():
        inputs = Variable(torch.from_numpy(x_train).cuda())
        labels = Variable(torch.from_numpy(y_train).cuda())
    else:
        inputs = Variable(torch.from_numpy(x_train))
        labels = Variable(torch.from_numpy(y_train))

    optimizer.zero_grad()     
    # Forward propagation
    outputs = model(inputs)
    
    loss = criterion(outputs, labels)
    
    # Backward propagation
    loss.backward()
    optimizer.step()
    
    # Logging
    print('epoch {}, loss {}'.format(epoch, loss.data[0]))

epoch 1, loss 0.010056260973215103
epoch 2, loss 0.009943963959813118
epoch 3, loss 0.009832892566919327
epoch 4, loss 0.009723102673888206
epoch 5, loss 0.009614513255655766
epoch 6, loss 0.009507164359092712
epoch 7, loss 0.009400964714586735
epoch 8, loss 0.009296050295233727
epoch 9, loss 0.00919220969080925
epoch 10, loss 0.009089595638215542
epoch 11, loss 0.00898805819451809
epoch 12, loss 0.008887704461812973
epoch 13, loss 0.008788492530584335
epoch 14, loss 0.008690289221704006
epoch 15, loss 0.008593233302235603
epoch 16, loss 0.008497300557792187
epoch 17, loss 0.008402449078857899
epoch 18, loss 0.00830857828259468
epoch 19, loss 0.008215810172259808
epoch 20, loss 0.008124018087983131


### Compare Data

In [7]:
if torch.cuda.is_available():
    predicted=model(Variable(torch.from_numpy(x_train).cuda())).data.cpu().numpy()
else:
    predicted=model(Variable(torch.from_numpy(x_train))).data.numpy()
predicted

array([[ 0.8323333],
       [ 2.856479 ],
       [ 4.880625 ],
       [ 6.90477  ],
       [ 8.928916 ],
       [10.953061 ],
       [12.977207 ],
       [15.001353 ],
       [17.025497 ],
       [19.049643 ],
       [21.073788 ]], dtype=float32)

In [8]:
y_train

array([[ 1.],
       [ 3.],
       [ 5.],
       [ 7.],
       [ 9.],
       [11.],
       [13.],
       [15.],
       [17.],
       [19.],
       [21.]], dtype=float32)

### Save & Retrieve the model

In [26]:
torch.save(model.state_dict(),'linearregression_model.pkl')

In [27]:
model.load_state_dict(torch.load('linearregression_model.pkl'))